### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'processImage'

### ISSUE THREAD

**Issue by niveditarufus** [robocomp/human-detection#1]
I tried to add the human-detection repo as a component into my current robocomp installation. I had to move the resources folder into src for these lines
`from resources.centroidtracker import CentroidTracker`
`from resources.trackableobject import TrackableObject` in specificworker.py. I also changed the url in the config to point to a mjpeg file hosted locally (via simplehttpserver).
Now I am able to reach till the detecting state. However I am getting an error at this line in `specificworker.py people = self.peopleserver_proxy.processImage(im, 1)`. I am guessing that this is because the config file doesnt have a "PeopleServerProxy" hence the error AttributeError: 'NoneType' object has no attribute 'processImage'. Any ideas on what "PeopleServerProxy" should be set to in the config file?

**Comment by rcintas** [comment]
It has been solved on https://github.com/robocomp/human-detection/commit/515276190968368071776e084dcf7049d5446632 commit.

Thanks niveditarufus

**Comment by rcintas** [comment]
solved
